apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    demo: sevice
spec:
  # list of containers
  containers:
  - name: nginx-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app:  nginx
    demo:  sevice
  ports:
  - protocol: TCP
    port: 80 #sevice-port
    targetPort: 80 #container-port