apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tire: frontend
spec:
 # modify replicas according to your case
  replicas: 3
  selector:  # replica-set labels
    matchLabels:
      app: nginx
      tire: frontend
  template:  # pod-defination
    metadata:
      labels:
        app: nginx
        tire: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine3.18-perl
